// Client
export const CLIENT_ADDED = 'CLIENT_ADDED';
export const CLIENT_DELETED = 'CLIENT_DELETED';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const CLIENT_UPDATED = 'CLIENT_UPDATED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';



