// Client
export const CLIENT_ADDED = 'CLIENT_ADDED';
export const CLIENT_DELETED = 'CLIENT_DELETED';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const CLIENT_UPDATED = 'CLIENT_UPDATED';
// Consultant
export const CONSULTANT_ADDED = 'CONSULTANT_ADDED';
export const CONSULTANT_DELETED = 'CONSULTANT_DELETED';
export const UPDATE_CONSULTANT = 'UPDATE_CONSULTANT';
export const CONSULTANT_UPDATED = 'CONSULTANT_UPDATED';
// Auth
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';



